// 沙箱要加载的默认资源配置
export const defaultAssetsConfig = {
  js: [
    'https://shengji.codewave.163.com/packages/sandbox@0.1.0/www/dependency/vue@2.6.11/umd/vue.min.js',
    'https://lcap-official-bucket.codewave.163.com/packages/@lcap/pc-ui@1.4.0/dist-theme/index.js',
  ],
  css: ['https://lcap-official-bucket.codewave.163.com/packages/@lcap/pc-ui@1.4.0/dist-theme/index.css'],
  theme: '',
};

// 子表单放置列模版
export const subFormDropColumnBlock = {
  concept: 'ViewElement',
  tag: 'u-table-view-column',
  slotScope: '',
  bindAttrs: [
    {
      concept: 'BindAttribute',
      name: 'width',
      type: 'string',
      value: '140',
    },
    {
      concept: 'BindAttribute',
      name: 'subFormDropColumn',
      type: 'static',
      value: true,
    },
    {
      concept: 'BindAttribute',
      name: 'subFormInitialColumn',
      type: 'string',
      value: 'drop',
    },
  ],
  bindEvents: [],
  children: [
    {
      concept: 'ViewElement',
      tag: 'template',
      slotTarget: 'title',
      slotScope: '',
      bindAttrs: [],
      bindEvents: [],
      children: [],
    },
    {
      concept: 'ViewElement',
      tag: 'template',
      slotTarget: 'cell',
      slotScope: 'current',
      bindAttrs: [],
      bindEvents: [],
      children: [],
    },
    {
      concept: 'ViewElement',
      tag: 'template',
      slotTarget: 'expander',
      slotScope: 'current',
      bindAttrs: [],
      bindEvents: [],
      children: [
        {
          concept: 'ViewElement',
          tag: 'u-table-view-expander',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'item',
              type: 'dynamic',
              value: '',
              expression: {
                concept: 'MemberExpression',
                name: '',
                object: {
                  concept: 'Identifier',
                  namespace: '',
                  name: 'current',
                },
                property: {
                  concept: 'Identifier',
                  namespace: '',
                  name: 'item',
                },
              },
            },
          ],
          bindEvents: [],
          children: [],
        },
      ],
    },
    {
      concept: 'ViewElement',
      tag: 'template',
      slotTarget: 'editcell',
      slotScope: 'current',
      bindAttrs: [],
      bindEvents: [],
      children: [],
    },
    {
      concept: 'ViewElement',
      tag: 'template',
      slotTarget: 'expand-content',
      slotScope: 'current',
      bindAttrs: [],
      bindEvents: [],
      children: [],
    },
  ],
};

// 组件物料
export const componentMaterials = [
  {
    group: 'Form',
    title: '表单',
    components: [
      {
        name: 'u-input',
        title: '单行输入',
        icon: 'input',
        category: 'Form',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-input',
        componentName: 'UInput',
        block: {
          concept: 'ViewElement',
          tag: 'u-input',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请输入',
            },
            {
              concept: 'BindAttribute',
              name: 'emptyValueIsNull',
              type: 'static',
              value: true,
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-number-input',
        title: '整数输入',
        icon: 'number',
        category: 'Form',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-number-input',
        componentName: 'UNumberInput',
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-number-input',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'decimalPlacesOmitZero',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'unitType',
              type: 'string',
              value: 'suffix',
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-number-input-decimal',
        title: '小数输入',
        icon: 'number-decimal',
        category: 'Form',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-number-input-decimal',
        componentName: 'UNumberInput',
        block: {
          concept: 'ViewElement',
          tag: 'u-number-input-decimal',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'decimalPlacesOmitZero',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'decimalPlacesValue',
              type: 'static',
              value: 2,
            },
            {
              concept: 'BindAttribute',
              name: 'decimalLength',
              type: 'static',
              value: 2,
            },
            {
              concept: 'BindAttribute',
              name: 'unitType',
              type: 'string',
              value: 'suffix',
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-textarea',
        title: '多行输入',
        icon: 'textarea',
        category: 'Form',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-textarea',
        componentName: 'UTextarea',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-textarea',
          staticStyle: '--custom-start: auto;min-width:initial;\nmax-width:min(240px,100%);',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请输入',
            },
            {
              concept: 'BindAttribute',
              name: 'limitPosition',
              type: 'string',
              value: 'outside',
            },
            {
              concept: 'BindAttribute',
              name: 'emptyValueIsNull',
              type: 'static',
              value: true,
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-radios',
        title: '单选组',
        icon: 'radios',
        category: 'Form',
        ideusage: {
          idetype: 'container',
        },
        tagName: 'u-radios',
        componentName: 'URadios',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-radios',
          slotScope: '',
          bindAttrs: [],
          children: [
            {
              concept: 'ViewElement',
              tag: 'u-radio',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'label',
                  type: 'string',
                  value: '1',
                },
              ],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  slotTarget: 'item',
                  bindAttrs: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '选项1',
                        },
                      ],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'u-radio',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'label',
                  type: 'string',
                  value: '2',
                },
              ],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  slotTarget: 'item',
                  bindAttrs: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '选项2',
                        },
                      ],
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
      {
        name: 'u-checkboxes',
        title: '多选组',
        icon: 'checkboxes',
        category: 'Form',
        ideusage: {
          idetype: 'container',
        },
        tagName: 'u-checkboxes',
        componentName: 'UCheckboxes',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-checkboxes',
          slotScope: '',
          bindAttrs: [],
          children: [
            {
              concept: 'ViewElement',
              tag: 'u-checkbox',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'label',
                  type: 'string',
                  value: '1',
                },
              ],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  slotTarget: 'item',
                  bindAttrs: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '选项1',
                        },
                      ],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'u-checkbox',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'label',
                  type: 'string',
                  value: '2',
                },
              ],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  slotTarget: 'item',
                  bindAttrs: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '选项2',
                        },
                      ],
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
      {
        name: 'u-uploader',
        title: '文件上传',
        icon: 'uploader',
        category: 'Form',
        ideusage: {
          idetype: 'container',
        },
        tagName: 'u-uploader',
        componentName: 'UUploader',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-uploader',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'display',
              type: 'string',
              value: 'inline',
            },
            {
              concept: 'BindAttribute',
              name: 'url',
              type: 'string',
              value: '/upload',
            },
            {
              concept: 'BindAttribute',
              name: 'urlField',
              type: 'string',
              value: 'filePath',
            },
            {
              concept: 'BindAttribute',
              name: 'limit',
              type: 'static',
              value: 10,
            },
            {
              concept: 'BindAttribute',
              name: 'fileIconSwitcher',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'downloadIconSwitcher',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'fileSize',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'maxSize',
              type: 'string',
              value: '50MB',
            },
            {
              concept: 'BindAttribute',
              name: 'converter',
              type: 'string',
              value: 'json',
            },
            {
              concept: 'BindAttribute',
              name: 'multiple',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'multipleOnce',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'fileConnectionGroup',
              type: 'string',
              value: 'lcap_default_connection',
            },
          ],
          children: [
            {
              concept: 'ViewElement',
              tag: 'template',
              slotTarget: 'file-list',
              slotScope: '',
              bindAttrs: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'i-ico',
                  staticStyle: 'margin: 0px 8px 0px 0px;',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'flag',
                      type: 'string',
                      value: 'file-icon',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'name',
                      type: 'string',
                      value: 'file-default',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'icotype',
                      type: 'string',
                      value: 'only',
                    },
                  ],
                  children: [],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-text',
                  staticStyle: 'margin: 0px 8px 0px 0px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; display: inherit;',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'flag',
                      type: 'string',
                      value: 'file-name',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'text',
                      type: 'string',
                      value: '文件名称',
                    },
                  ],
                  children: [],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-text',
                  staticStyle: 'margin: 0px 8px 0px 0px;',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'flag',
                      type: 'string',
                      value: 'file-size',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'text',
                      type: 'string',
                      value: '文件大小',
                    },
                  ],
                  children: [],
                },
                {
                  concept: 'ViewElement',
                  tag: 'i-ico',
                  staticStyle: 'margin: 0px 8px 0px 0px;',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'flag',
                      type: 'string',
                      value: 'download-icon',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'name',
                      type: 'string',
                      value: 'download',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'icotype',
                      type: 'string',
                      value: 'only',
                    },
                  ],
                  children: [],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'u-button',
              slotScope: '',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'color',
                  type: 'string',
                  value: 'primary',
                },
                {
                  concept: 'BindAttribute',
                  name: 'icon',
                  type: 'string',
                  value: 'upload',
                },
                {
                  concept: 'BindAttribute',
                  name: 'text',
                  type: 'string',
                  value: '文件上传',
                },
              ],
              children: [],
            },
            {
              concept: 'ViewElement',
              tag: 'template',
              slotTarget: 'dragDescription',
              slotScope: '',
              bindAttrs: [],
              bindEvents: [],
              bindDirectives: [],
              bindStyles: [],
              children: [],
            },
          ],
        },
      },
    ],
  },
  {
    group: 'Selector',
    title: '选择器',
    components: [
      {
        name: 'u-select',
        title: '选择器',
        icon: 'select',
        category: 'Selector',
        ideusage: {
          idetype: 'container',
        },
        tagName: 'u-select',
        componentName: 'USe lect',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-select',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请选择',
            },
            {
              concept: 'BindAttribute',
              name: 'pagination',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'pageSize',
              type: 'static',
              value: 50,
            },
            {
              concept: 'BindAttribute',
              name: 'emptyValueIsNull',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'appendTo',
              type: 'string',
              value: 'body',
            },
          ],
          children: [
            {
              concept: 'ViewElement',
              tag: 'template',
              slotTarget: 'option',
              slotScope: 'current',
              bindAttrs: [],
              children: [],
            },
            {
              concept: 'ViewElement',
              tag: 'template',
              slotTarget: 'renderFooter',
              slotScope: '',
              bindAttrs: [],
              children: [],
            },
          ],
        },
      },
      {
        name: 'u-region-select',
        title: '地区选择',
        icon: 'region-select',
        category: 'Selector',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-region-select',
        componentName: 'URegionSelect',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-region-select',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'converter',
              type: 'string',
              value: 'name',
            },
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请选择地区',
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-date-picker',
        title: '日期选择',
        icon: 'date-picker',
        category: 'Selector',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-date-picker',
        componentName: 'UDatePicker',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-date-picker',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'emptyValueIsNull',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'startDate',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'endDate',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请选择日期',
            },
          ],
          children: [],
        },
      },
      {
        name: 'u-time-picker',
        title: '时间选择',
        icon: 'time-picker',
        category: 'Selector',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-time-picker',
        componentName: 'UTimePicker',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-time-picker',
          staticStyle: '--custom-start: auto;min-width:initial;\nmax-width:min(240px,100%);',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'startTime',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'endTime',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请选择时间',
            },
          ],
          bindEvents: [],
          bindDirectives: [],
          bindStyles: [],
          children: [],
        },
      },
      {
        name: 'u-date-time-picker',
        title: '日期时间选择',
        icon: 'date-time-picker',
        category: 'Selector',
        ideusage: {
          idetype: 'element',
        },
        tagName: 'u-date-time-picker',
        componentName: 'UDateTimePicker',
        screenshots: [],
        drawings: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-date-time-picker',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'emptyValueIsNull',
              type: 'static',
              value: true,
            },
            {
              concept: 'BindAttribute',
              name: 'converter',
              type: 'string',
              value: 'json',
            },
            {
              concept: 'BindAttribute',
              name: 'startDate',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'endDate',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
            {
              concept: 'BindAttribute',
              name: 'placeholder',
              type: 'string',
              value: '请选择时间',
            },
          ],
          children: [],
        },
      },
    ],
  },
  {
    group: 'Advanced',
    title: '高级',
    components: [
      {
        componentName: 'USubForm',
        name: 'u-sub-form',
        tagName: 'u-sub-form',
        title: '子表单',
        category: 'Advanced',
        icon: 'form',
        drawings: [],
        screenshots: [],
        block: {
          concept: 'ViewElement',
          tag: 'u-linear-layout',
          slotScope: '',
          bindAttrs: [
            { concept: 'BindAttribute', name: 'wrap', type: 'static', value: true },
            { concept: 'BindAttribute', name: 'mode', type: 'string', value: 'flex' },
            { concept: 'BindAttribute', name: 'direction', type: 'string', value: 'vertical' },
            { concept: 'BindAttribute', name: 'justify', type: 'string', value: 'start' },
            { concept: 'BindAttribute', name: 'alignment', type: 'string', value: 'start' },
            { concept: 'BindAttribute', name: 'subFormLayout', type: 'static', value: true },
          ],
          children: [
            {
              concept: 'ViewElement',
              tag: 'u-linear-layout',
              slotScope: '',
              bindAttrs: [
                { concept: 'BindAttribute', name: 'direction', type: 'string', value: 'horizontal', playground: [] },
                { concept: 'BindAttribute', name: 'wrap', type: 'static', value: true, playground: [] },
                { concept: 'BindAttribute', name: 'operateType', type: 'string', value: 'operateRowList', playground: [] },
              ],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'u-button',
                  slotScope: '',
                  bindAttrs: [
                    { concept: 'BindAttribute', name: 'color', type: 'string', value: 'primary', playground: [] },
                    { concept: 'BindAttribute', name: 'text', type: 'string', value: '添 加', playground: [] },
                    { concept: 'BindAttribute', name: 'subFormBtnType', type: 'string', value: 'addBtn', playground: [] },
                  ],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-button',
                  staticStyle: '--custom-start: auto; display: none;',
                  slotScope: '',
                  bindAttrs: [
                    { concept: 'BindAttribute', name: 'color', type: 'string', value: 'default', playground: [] },
                    { concept: 'BindAttribute', name: 'text', type: 'string', value: '导 出', playground: [] },
                    { concept: 'BindAttribute', name: 'subFormBtnType', type: 'string', value: 'exportBtn', playground: [] },
                  ],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'u-validator',
              staticStyle: 'width:100%;',
              slotScope: '',
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'label',
                  type: 'string',
                  value: '子表单',
                },
              ],
              bindEvents: [],
              bindDirectives: [],
              bindStyles: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'u-table-view',
                  staticStyle: '--custom-start: auto; width: min(360px, 100%);',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'pageSize',
                      type: 'static',
                      value: 20,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'pageNumber',
                      type: 'static',
                      value: 1,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'subForm',
                      type: 'static',
                      value: true,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'value',
                      type: 'dynamic',
                      value: '',
                      sync: true,
                      expression: null,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'values',
                      type: 'dynamic',
                      value: '',
                      sync: true,
                      expression: null,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'pagination',
                      type: 'static',
                      value: false,
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'showSizer',
                      type: 'static',
                      value: true,
                    },
                  ],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-table-view-column',
                      slotScope: '',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'type',
                          type: 'string',
                          value: 'index',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'width',
                          type: 'string',
                          value: '60',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'subFormInitialColumn',
                          type: 'string',
                          value: 'index',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'fixed',
                          type: 'static',
                          value: true,
                        },
                      ],
                      children: [
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'title',
                          slotScope: '',
                          bindAttrs: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-text',
                              slotScope: '',
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'text',
                                  type: 'string',
                                  value: '序号',
                                },
                              ],
                              bindEvents: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'cell',
                          slotScope: 'current',
                          bindAttrs: [],
                          children: [],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'expander',
                          slotScope: 'current',
                          bindAttrs: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-table-view-expander',
                              slotScope: '',
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'item',
                                  type: 'dynamic',
                                  value: '',
                                  expression: {
                                    concept: 'MemberExpression',
                                    name: '',
                                    object: {
                                      concept: 'Identifier',
                                      namespace: '',
                                      name: 'current',
                                    },
                                    property: {
                                      concept: 'Identifier',
                                      namespace: '',
                                      name: 'item',
                                    },
                                  },
                                },
                              ],
                              bindEvents: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'editcell',
                          slotScope: 'current',
                          bindAttrs: [],
                          children: [],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'expand-content',
                          slotScope: 'current',
                          bindAttrs: [],
                          children: [],
                        },
                      ],
                    },
                    subFormDropColumnBlock,
                    {
                      concept: 'ViewElement',
                      tag: 'u-table-view-column',
                      slotScope: '',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'width',
                          type: 'string',
                          value: '160',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'subFormInitialColumn',
                          type: 'string',
                          value: 'action',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'operateType', // 操作列表
                          type: 'string',
                          value: 'operateColumnList',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'fixed',
                          type: 'static',
                          value: true,
                        },
                      ],
                      bindEvents: [],
                      children: [
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'title',
                          slotScope: '',
                          bindAttrs: [],
                          bindEvents: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-text',
                              slotScope: '',
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'text',
                                  type: 'string',
                                  value: '操作',
                                },
                              ],
                              bindEvents: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'cell',
                          slotScope: 'current',
                          bindAttrs: [],
                          bindEvents: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-linear-layout',
                              slotScope: '',
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'direction',
                                  type: 'string',
                                  value: 'horizontal',
                                },
                                {
                                  concept: 'BindAttribute',
                                  name: 'wrap',
                                  type: 'static',
                                  value: true,
                                },
                              ],
                              bindEvents: [],
                              children: [
                                {
                                  concept: 'ViewElement',
                                  tag: 'u-link',
                                  slotScope: '',
                                  bindAttrs: [
                                    {
                                      concept: 'BindAttribute',
                                      name: 'text',
                                      type: 'string',
                                      value: '复制',
                                    },
                                    {
                                      concept: 'BindAttribute',
                                      name: 'subFormBtnType',
                                      type: 'string',
                                      value: 'copyLink',
                                    },
                                  ],
                                  bindEvents: [],
                                  children: [],
                                },
                                {
                                  concept: 'ViewElement',
                                  tag: 'u-link',
                                  name: 'link_2',
                                  slotScope: '',
                                  bindAttrs: [
                                    {
                                      concept: 'BindAttribute',
                                      name: 'text',
                                      type: 'string',
                                      value: '删除',
                                    },
                                    {
                                      concept: 'BindAttribute',
                                      name: 'subFormBtnType',
                                      type: 'string',
                                      value: 'deleteLink',
                                    },
                                  ],
                                  bindEvents: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'expander',
                          slotScope: 'current',
                          bindAttrs: [],
                          bindEvents: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-table-view-expander',
                              slotScope: '',
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'item',
                                  type: 'dynamic',
                                  value: '',
                                  expression: {
                                    concept: 'MemberExpression',
                                    folded: false,
                                    name: '',
                                    object: {
                                      concept: 'Identifier',
                                      namespace: '',
                                      name: 'current',
                                      folded: false,
                                    },
                                    property: {
                                      concept: 'Identifier',
                                      namespace: '',
                                      name: 'item',
                                      folded: false,
                                    },
                                  },
                                  playground: [],
                                },
                              ],
                              bindEvents: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'editcell',
                          slotScope: 'current',
                          bindRoles: [],
                          bindEvents: [],
                          children: [],
                        },
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          slotTarget: 'expand-content',
                          slotScope: 'current',
                          bindAttrs: [],
                          bindEvents: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
    ],
  },
];

export function getComponentMaterial(tagName) {
  return componentMaterials.flatMap((item) => item.components).find((component) => component.tagName === tagName);
}

export function getComponentBlock(tagName) {
  return getComponentMaterial(tagName)?.block ?? null;
}

// 初始布局
export const initLayoutEmpty = JSON.stringify({
  concept: 'View',
  name: 'form_designer',
  title: '未命名表单',
  elements: [
    {
      concept: 'ViewElement',
      tag: 'u-linear-layout',
      name: 'uLinearLayout1',
      staticClass: null,
      // staticStyle: 'background:#fff;  --custom-start: auto;',
      slotTarget: null,
      slotScope: null,
      bindAttrs: [
        { concept: 'BindAttribute', name: 'type', type: 'string', value: 'root', rules: [], playground: [] },
        { concept: 'BindAttribute', name: 'gap', type: 'string', value: 'none', rules: [], playground: [] },
      ],
      children: [
        {
          concept: 'ViewElement',
          tag: 'u-form',
          name: 'form_1',
          staticStyle: 'padding:16px; --custom-start: auto; align-content: flex-start; min-height: 400px;',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'layout',
              type: 'string',
              value: 'inline-flex',
            },
            {
              concept: 'BindAttribute',
              name: 'repeat',
              type: 'static',
              value: 2,
            },
            {
              concept: 'BindAttribute',
              name: 'labelLayout',
              type: 'string',
              value: 'inline',
            },
          ],
          children: [],
        },
        {
          concept: 'ViewElement',
          tag: 'u-modal',
          name: 'delInfoModal',
          slotScope: '',
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'icon',
              type: 'string',
              value: 'warning',
            },
            {
              concept: 'BindAttribute',
              name: 'visible',
              type: 'dynamic',
              value: '',
              sync: true,
              expression: null,
            },
          ],
          bindEvents: [],
          children: [
            {
              concept: 'ViewElement',
              tag: 'template',
              name: 'template_1',
              slotTarget: 'foot',
              slotScope: '',
              bindAttrs: [],
              bindEvents: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'u-linear-layout',
                  name: 'linear_layout_1',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'justify',
                      type: 'string',
                      value: 'end',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'gap',
                      type: 'string',
                      value: 'normal',
                    },
                  ],
                  bindEvents: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      name: 'button_1',
                      tag: 'u-button',
                      slotScope: '',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '取 消',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'subFormBtnType',
                          type: 'string',
                          value: 'cancelBtn',
                        },
                      ],
                      bindEvents: [
                        {
                          concept: 'BindEvent',
                          name: 'click',
                          logics: [
                            {
                              concept: 'Logic',
                              name: 'cancelInfo',
                              body: `await this.$refs?.delInfoModal?.close?.();\n`,
                            },
                          ],
                        },
                      ],
                      children: [],
                    },
                    {
                      concept: 'ViewElement',
                      name: 'button_2',
                      tag: 'u-button',
                      slotScope: '',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'color',
                          type: 'string',
                          value: 'primary',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '确 定',
                        },
                        {
                          concept: 'BindAttribute',
                          name: 'subFormBtnType',
                          type: 'string',
                          value: 'confirmBtn',
                        },
                      ],
                      bindEvents: [
                        {
                          concept: 'BindEvent',
                          name: 'click',
                          logics: [
                            {
                              concept: 'Logic',
                              name: 'confirmInfo',
                              body: `this.delSubFormDataSource?.splice?.(this.delInfoIndex, 1); \nawait this.$refs?.delInfoModal?.close?.();`,
                            },
                          ],
                        },
                      ],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'template',
              name: 'template_2',
              slotTarget: 'body',
              slotScope: '',
              bindAttrs: [],
              bindEvents: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'u-text',
                  name: 'text_1',
                  staticStyle: 'font-size:18px;font-weight:bold;',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'text',
                      type: 'string',
                      value: '请确认是否删除？',
                    },
                  ],
                  bindEvents: [],
                  children: [],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-linear-layout',
                  name: 'linear_layout_2',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'direction',
                      type: 'string',
                      value: 'horizontal',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'wrap',
                      type: 'static',
                      value: true,
                    },
                  ],
                  bindEvents: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      name: 'text_2',
                      slotScope: '',
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '删除后将无法恢复，请谨慎操作',
                        },
                      ],
                      bindEvents: [],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'template',
              name: 'template_3',
              slotTarget: 'title',
              slotScope: '',
              bindAttrs: [],
              bindEvents: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'u-text',
                  name: 'text_3',
                  slotScope: '',
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'text',
                      type: 'string',
                      value: '删除',
                    },
                  ],
                  bindEvents: [],
                  children: [],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'template',
              name: 'template_4',
              slotTarget: 'heading',
              slotScope: '',
              bindAttrs: [],
              bindEvents: [],
              children: [],
            },
          ],
        },
      ],
    },
  ],
  variables: [],
  entities: [],
});

export const initLayout = JSON.stringify({
  concept: 'View',
  name: 'form_designer',
  title: '未命名表单',
  elements: [
    {
      concept: 'ViewElement',
      tag: 'u-linear-layout',
      name: 'uLinearLayout1',
      staticClass: null,
      staticStyle: 'height:100%; background:#fff;  --custom-start: auto; min-height: 400px;',
      slotTarget: null,
      slotScope: null,
      bindRoles: [],
      cssRules: [],
      bindAttrs: [
        { concept: 'BindAttribute', name: 'type', type: 'string', value: 'root', rules: [], playground: [] },
        { concept: 'BindAttribute', name: 'gap', type: 'string', value: 'none', rules: [], playground: [] },
      ],
      bindEvents: [],
      bindDirectives: [],
      bindStyles: [],
      children: [
        {
          concept: 'ViewElement',
          tag: 'u-form',
          name: 'form_1',
          staticStyle: 'min-height:100%; padding:16px; --custom-start: auto; align-content: flex-start;',
          bindRoles: [],
          cssRules: [],
          bindAttrs: [
            {
              concept: 'BindAttribute',
              name: 'layout',
              type: 'string',
              value: 'inline-flex',
            },
            {
              concept: 'BindAttribute',
              name: 'repeat',
              type: 'static',
              value: 2,
            },
            {
              concept: 'BindAttribute',
              name: 'labelLayout',
              type: 'string',
              value: 'inline',
            },
            {
              concept: 'BindAttribute',
              name: 'bindEntity',
              type: 'string',
              value: 'Form_1qrk3a',
            },
          ],
          bindEvents: [],
          bindDirectives: [],
          bindStyles: [],
          children: [
            {
              concept: 'ViewElement',
              tag: 'u-form-item',
              name: 'form_item_1',
              slotScope: '',
              bindRoles: [],
              cssRules: [],
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'required',
                  type: 'static',
                  value: true,
                },
                {
                  concept: 'BindAttribute',
                  name: 'layout',
                  type: 'string',
                  value: 'center',
                },
                {
                  concept: 'BindAttribute',
                  name: 'rules',
                  rules: [
                    {
                      concept: 'ValidationRule',
                      calleeNamespace: 'nasl.validation',
                      calleeName: 'required',
                      enableServerValidation: false,
                      folded: false,
                      errorMessage: {
                        value: '必填哦',
                        folded: false,
                      },
                      arguments: [],
                    },
                  ],
                },
              ],
              bindEvents: [],
              bindDirectives: [],
              bindStyles: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  name: 'template_1',
                  slotTarget: 'label',
                  slotScope: '',
                  bindRoles: [],
                  cssRules: [],
                  bindAttrs: [],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      name: 'text_1',
                      slotScope: '',
                      bindRoles: [],
                      cssRules: [],
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '名称',
                        },
                      ],
                      bindEvents: [],
                      bindDirectives: [],
                      bindStyles: [],
                      children: [],
                    },
                  ],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-input',
                  name: 'input_1',
                  slotScope: '',
                  bindRoles: [],
                  cssRules: [],
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'placeholder',
                      type: 'string',
                      value: '由字母、数字和中划线组成',
                    },
                    {
                      concept: 'BindAttribute',
                      name: 'value',
                      type: 'dynamic',
                      value: '',
                      sync: true,
                      expression: {
                        concept: 'MemberExpression',
                        folded: false,
                        object: {
                          concept: 'Identifier',
                          name: 'Form_1qrk3a',
                          folded: false,
                        },
                        property: {
                          concept: 'Identifier',
                          name: 'property1',
                          folded: false,
                        },
                      },
                    },
                  ],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [],
                },
              ],
            },
            {
              concept: 'ViewElement',
              tag: 'u-form-item',
              name: 'form_item_2',
              slotScope: '',
              bindRoles: [],
              cssRules: [],
              bindAttrs: [
                {
                  concept: 'BindAttribute',
                  name: 'required',
                  type: 'static',
                  value: true,
                },
                {
                  concept: 'BindAttribute',
                  name: 'layout',
                  type: 'string',
                  value: 'center',
                },
                {
                  concept: 'BindAttribute',
                  name: 'rules',
                  rules: [
                    {
                      concept: 'ValidationRule',
                      calleeNamespace: 'nasl.validation',
                      calleeName: 'required',
                      enableServerValidation: false,
                      folded: false,
                      errorMessage: {
                        value: '类型不能为空哦',
                        folded: false,
                      },
                      arguments: [],
                    },
                  ],
                },
              ],
              bindEvents: [],
              bindDirectives: [],
              bindStyles: [],
              children: [
                {
                  concept: 'ViewElement',
                  tag: 'template',
                  name: 'template_2',
                  slotTarget: 'label',
                  slotScope: '',
                  bindRoles: [],
                  cssRules: [],
                  bindAttrs: [],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-text',
                      name: 'text_2',
                      slotScope: '',
                      bindRoles: [],
                      cssRules: [],
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'text',
                          type: 'string',
                          value: '类型',
                        },
                      ],
                      bindEvents: [],
                      bindDirectives: [],
                      bindStyles: [],
                      children: [],
                    },
                  ],
                },
                {
                  concept: 'ViewElement',
                  tag: 'u-radios',
                  name: 'radios_1',
                  slotScope: '',
                  bindRoles: [],
                  cssRules: [],
                  bindAttrs: [
                    {
                      concept: 'BindAttribute',
                      name: 'value',
                      type: 'dynamic',
                      value: '',
                      sync: true,
                      expression: {
                        concept: 'MemberExpression',
                        folded: false,
                        object: {
                          concept: 'Identifier',
                          name: 'Form_1qrk3a',
                          folded: false,
                        },
                        property: {
                          concept: 'Identifier',
                          name: 'property2',
                          folded: false,
                        },
                      },
                    },
                  ],
                  bindEvents: [],
                  bindDirectives: [],
                  bindStyles: [],
                  children: [
                    {
                      concept: 'ViewElement',
                      tag: 'u-radio',
                      name: 'radio_1',
                      slotScope: '',
                      bindRoles: [],
                      cssRules: [],
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'label',
                          type: 'string',
                          value: 'A',
                        },
                      ],
                      bindEvents: [],
                      bindDirectives: [],
                      bindStyles: [],
                      children: [
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          name: 'template_3',
                          slotTarget: 'item',
                          slotScope: '',
                          bindRoles: [],
                          cssRules: [],
                          bindAttrs: [],
                          bindEvents: [],
                          bindDirectives: [],
                          bindStyles: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-text',
                              name: 'text_3',
                              slotScope: '',
                              bindRoles: [],
                              cssRules: [],
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'text',
                                  type: 'string',
                                  value: '类型 A',
                                },
                              ],
                              bindEvents: [],
                              bindDirectives: [],
                              bindStyles: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      concept: 'ViewElement',
                      tag: 'u-radio',
                      name: 'radio_2',
                      slotScope: '',
                      bindRoles: [],
                      cssRules: [],
                      bindAttrs: [
                        {
                          concept: 'BindAttribute',
                          name: 'label',
                          type: 'string',
                          value: 'B',
                        },
                      ],
                      bindEvents: [],
                      bindDirectives: [],
                      bindStyles: [],
                      children: [
                        {
                          concept: 'ViewElement',
                          tag: 'template',
                          name: 'template_4',
                          slotTarget: 'item',
                          slotScope: '',
                          bindRoles: [],
                          cssRules: [],
                          bindAttrs: [],
                          bindEvents: [],
                          bindDirectives: [],
                          bindStyles: [],
                          children: [
                            {
                              concept: 'ViewElement',
                              tag: 'u-text',
                              name: 'text_4',
                              slotScope: '',
                              bindRoles: [],
                              cssRules: [],
                              bindAttrs: [
                                {
                                  concept: 'BindAttribute',
                                  name: 'text',
                                  type: 'string',
                                  value: '类型 B',
                                },
                              ],
                              bindEvents: [],
                              bindDirectives: [],
                              bindStyles: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      concept: 'ViewElement',
                      tag: 'template',
                      name: 'template_5',
                      slotTarget: 'item',
                      slotScope: 'current',
                      bindRoles: [],
                      cssRules: [],
                      bindAttrs: [],
                      bindEvents: [],
                      bindDirectives: [],
                      bindStyles: [],
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  variables: [
    {
      concept: 'Variable',
      name: 'Form_1qrk3a',
      typeAnnotation: {
        concept: 'TypeAnnotation',
        typeKind: 'reference',
        typeNamespace: 'entities',
        typeName: 'Form_1qrk3a',
      },
    },
  ],
  entities: [
    {
      concept: 'Entity',
      name: 'Form_1qrk3a', // 实体名称，按照mini-nasl的规范生成
      uuid: '6e55ddce29cc4b8db357813a16f23789',
      tableName: 'Form_1qrk3a', // 数据库表名，可能与name不一致，表单中更改的是这个值
      origin: 'form',
      properties: [
        {
          concept: 'EntityProperty',
          name: 'id',
          uuid: '0ac75198c2624a1baf235088577033f1',
          columnName: 'id',
          label: '主键',
          description: '主键',
          primaryKey: true,
          typeAnnotation: {
            concept: 'TypeAnnotation',
            typeKind: 'primitive',
            typeNamespace: 'nasl.core',
            typeName: 'Long',
          },
        },
        {
          concept: 'EntityProperty',
          name: 'property1',
          uuid: 'e022db87ec034629b6be29aa33f18887',
          columnName: 'property1',
          label: '名称',
          typeAnnotation: {
            concept: 'TypeAnnotation',
            typeKind: 'primitive',
            typeNamespace: 'nasl.core',
            typeName: 'String',
          },
        },
        {
          concept: 'EntityProperty',
          name: 'property2',
          uuid: '03926ac5587e43d08df90cc229fbb5b7',
          columnName: 'property2',
          label: '类型',
          typeAnnotation: {
            concept: 'TypeAnnotation',
            typeKind: 'primitive',
            typeNamespace: 'nasl.core',
            typeName: 'String',
          },
        },
      ],
    },
  ],
});
