module.exports = {
    type: 'component',
    docs: {
        components: [
            { group: '组件', name: 'cw-antd-custom-view',path: "./components/cw-antd-custom-view/api.yaml"},
            { group: '组件', name: 'cw-antd-custom-render-view', path: "./components/cw-antd-custom-render-view/api.yaml" },
            { group: '组件', name: 'cw-antd-custom-table',path: "./components/cw-antd-custom-table/api.yaml"},,
            { group: '组件', name: 'cw-antd-input',path: "./components/cw-antd-input/api.yaml"},
            { group: '组件', name: 'cw-antd-input-number',path: "./components/cw-antd-input-number/api.yaml"},
            { group: '组件', name: 'cw-antd-select',path: "./components/cw-antd-select/api.yaml"},
            { group: '组件', name: 'cw-antd-textarea',path: "./components/cw-antd-textarea/api.yaml"},,
            { group: '组件', name: 'cw-antd-auto-complete',path: "./components/cw-antd-auto-complete/api.yaml"},,
            { group: '组件', name: 'cw-antd-checkbox',path: "./components/cw-antd-checkbox/api.yaml"},,
            { group: '组件', name: 'cw-antd-radio',path: "./components/cw-antd-radio/api.yaml"},,
            { group: '组件', name: 'cw-antd-switch',path: "./components/cw-antd-switch/api.yaml"},,
            { group: '组件', name: 'cw-antd-time-picker',path: "./components/cw-antd-time-picker/api.yaml"},,
            { group: '组件', name: 'cw-antd-date-picker',path: "./components/cw-antd-date-picker/api.yaml"},,
            { group: '组件', name: 'cw-antd-range-picker', path: "./components/cw-antd-range-picker/api.yaml" }, ,
            // { group: '组件', name: 'cw-add-rule-view',path: "./components/cw-add-rule-view/api.yaml"},
            // { group: '组件', name: 'cw-antd-upload',path: "./components/cw-antd-upload/api.yaml"},
            // { group: '组件', name: 'cw-antd-card',path: "./components/cw-antd-card/api.yaml"},
            // { group: '组件', name: 'cw-antd-button',path: "./components/cw-antd-button/api.yaml"},
            // { group: '组件', name: 'cw-antd-icon',path: "./components/cw-antd-icon/api.yaml"},
            // { group: '组件', name: 'cw-add-dependency-view',path: "./components/cw-add-dependency-view/api.yaml"},
            // { group: '组件', name: 'cw-add-data-source-view',path: "./components/cw-add-data-source-view/api.yaml"},
            // { group: '组件', name: 'cw-antd-calendar',path: "./components/cw-antd-calendar/api.yaml"},
            { group: '组件', name: 'cw-antd-form-table',path: "./components/cw-antd-form-table/api.yaml"},,
            // { group: '组件', name: 'cw-antd-cascader',path: "./components/cw-antd-cascader/api.yaml"},,
            // { group: '组件', name: 'cw-antd-test',path: "./components/cw-antd-test/api.yaml"},,
            // { group: '组件', name: 'cw-antd-nested-emample',path: "./components/cw-antd-nested-emample/api.yaml"},,
            // { group: '组件', name: 'cw-antd-action-table',path: "./components/cw-antd-action-table/api.yaml"},,
            // { group: '组件', name: 'cw-tree-select',path: "./components/cw-tree-select/api.yaml"},,
            // { group: '组件', name: 'cw-antd-affix',path: "./components/cw-antd-affix/api.yaml"},
            // { group: '组件', name: 'cw-antd-dropdown',path: "./components/cw-antd-dropdown/api.yaml"},
            // { group: '组件', name: 'cw-antd-steps',path: "./components/cw-antd-steps/api.yaml"},
           
            // { group: '组件', name: 'cw-add-select-source-view',path: "./components/cw-add-select-source-view/api.yaml"},,
            { group: '组件', name: 'cw-antd-image',path: "./components/cw-antd-image/api.yaml"},,
            { group: '组件', name: 'cw-antd-text',path: "./components/cw-antd-text/api.yaml"},,
            { group: '组件', name: 'cw-antd-upload',path: "./components/cw-antd-upload/api.yaml"},,
            { group: '组件', name: 'cw-antd-checkbox-with-input',path: "./components/cw-antd-checkbox-with-input/api.yaml"},,
            // Conponents Route List
        ],
    },
};
