export const fakeData = [
    {
        category: {
            id: 111,
            createdTime: null,
            updatedTime: null,
            createdBy: null,
            updatedBy: null,
            label: '全部风险全',
            explanation: '这是全部风险',
            pid: 0,
            levellabel: '全部风险',
        },
    },
    {
        category: {
            id: 12,
            createdTime: '2023-05-24T00:57:48.000Z',
            updatedTime: '2023-05-24T00:57:48.000Z',
            createdBy: '奇欣欣',
            updatedBy: null,
            label: '法律3风',
            explanation: '这是法律风险',
            pid: 111,
            levellabel: '全部风险/法律风险',
        },
    },
    {
        category: {
            id: 182,
            createdTime: '2023-05-24T00:57:48.000Z',
            updatedTime: '2023-05-24T00:57:48.000Z',
            createdBy: '奇欣欣',
            updatedBy: null,
            label: '法律风险',
            explanation: '这是法律风险',
            pid: 12,
            levellabel: '全部风险/法律风险',
        },
    },
    {
        category: {
            id: 201,
            createdTime: '2023-05-24T00:57:48.000Z',
            updatedTime: '2023-05-24T00:57:48.000Z',
            createdBy: '奇欣欣',
            updatedBy: null,
            label: '法律风险',
            explanation: '这是法律风险',
            pid: 111,
            levellabel: '全部风险/法律风险',
        },
    },
    {
        category: {
            id: 210,
            createdTime: '2023-05-24T00:57:48.000Z',
            updatedTime: '2023-05-24T00:57:48.000Z',
            createdBy: '奇欣欣',
            updatedBy: null,
            label: '法律风险',
            explanation: '这是法律风险',
            pid: 182,
            levellabel: '全部风险/法律风险',
        },
    },
    {
        category: {
            id: 211,
            createdTime: '2023-05-24T00:57:48.000Z',
            updatedTime: '2023-05-24T00:57:48.000Z',
            createdBy: '奇欣欣',
            updatedBy: null,
            label: '法律风险',
            explanation: '这是法律风险',
            pid: 182,
            levellabel: '全部风险/法律风险',
        },
    },
];
