name: Build Changed Packages & Upload Artifacts

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

jobs:
  plan:
    name: Plan matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.plan.outputs.matrix }}
      count: ${{ steps.plan.outputs.count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要完整历史才能 diff

      - name: Setup Git (make sure origin/main exists)
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* || true

      - name: Generate matrix
        id: plan
        shell: bash
        run: |
          node scripts/ci/plan-changed-packages.mjs > matrix.json

          # 只把 include 数组写入到输出
          {
            echo 'matrix<<EOF'
            jq -c '.include' matrix.json
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

          COUNT=$(jq '.include | length' matrix.json)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          echo "Planned jobs: $COUNT"
          echo "Diff range: $(jq -r '.range' matrix.json)"

  build:
    name: Build ${{ matrix.name }}
    needs: plan
    if: needs.plan.outputs.count != '0'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.plan.outputs.matrix) }}

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ✅ Step 1: 安装 Node
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # ✅ Step 2: 若存在 lockfile，则启用 npm 缓存
      - name: Enable npm cache (if lockfile exists)
        if: ${{ hashFiles(format('{0}/package-lock.json', matrix.dir)) != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: ${{ matrix.dir }}/package-lock.json

      # ✅ Step 3: 安装全局 LCAP CLI（仅 Node14/16 环境执行）
      - name: Install global LCAP CLI
        if: matrix.node == '14' || matrix.node == '16'
        run: |
          echo "Installing LCAP globally..."
          npm install -g lcap@latest || (echo "⚠️ Failed to install lcap" && exit 1)
          which lcap || echo "⚠️ lcap not in PATH"
          lcap --version || echo "LCAP installed but version not shown"

      # ✅ Step 4: 执行构建命令
      - name: Install & Build (per package)
        run: |
          set -e
          echo "Run in: $(pwd)"
          cat > /tmp/build-steps.js <<'NODE'
          const { execSync } = require('child_process');
          const steps = ${{ toJson(matrix.build) }};
          for (const cmd of steps) {
            console.log(`+ ${cmd}`);
            execSync(cmd, { stdio: 'inherit', shell: true });
          }
          NODE
          node /tmp/build-steps.js

      # ✅ Step 5: 上传 zip 产物（形如 ***@*.*.*.zip）
      - name: Upload ZIP artifact (if any)
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles(format('{0}/*@*.*.*.zip', matrix.dir)) != '' }}
        with:
          name: ${{ matrix.name }}.zip
          path: ${{ matrix.dir }}/*@*.*.*.zip
          retention-days: 7

      # ✅ Step 6: 上传 dist-theme（若存在）
      - name: Upload dist-theme (if present)
        uses: actions/upload-artifact@v4
        if: ${{ hashFiles(format('{0}/dist-theme/**', matrix.dir)) != '' }}
        with:
          name: ${{ matrix.name }}-dist-theme
          path: ${{ matrix.dir }}/dist-theme/**
          retention-days: 7
