name: Update Pull Request Body

on:
    pull_request:
        branches: main

permissions:
    pull-requests: write

jobs:
    update-pr:
        runs-on: ubuntu-latest

        steps:
            - name: Check if commit is from CI
              run: |
                  if [[ "${{ github.event.head_commit.committer.username }}" == "github-actions[bot]" ]]; then
                    echo "Commit is from CI, skipping the build..."
                    exit 78
                  else
                    echo "Commit is not from CI, continuing with the build..."
                  fi
            - name: Checkout
              uses: actions/checkout/@v3
              with:
                  fetch-depth: 0

            - name: Git Identity
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
                  git checkout -b main origin/main
                  git checkout '${{github.event.pull_request.head.ref}}'
              env:
                  GITHUB_TOKEN: ${{ github.token}}

            - name: Setup Nodejs
              uses: actions/setup-node@v3
              with:
                  cache: 'yarn'
                  node-version: 16

            - name: Install yarn
              run: npm install -g yarn@v1

            - name: Install Dep
              run: |
                  yarn install --frozen-lockfile

            - name: Update Pull Request
              run: |
                  yarn changelog:ci
              env:
                  GITHUB_TOKEN: ${{ github.token}}
                  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
